package br.com.correios.webservice.postagem

import javax.xml.ws.WebFault

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebFault(name = "Exception", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
class ExceptionException : java.lang.Exception {

    var faultInfo: Exception
        private set

    constructor(message: String?, faultInfo: Exception) : super(message) {
        this.faultInfo = faultInfo
    }

    constructor(message: String?, faultInfo: Exception, cause: Throwable?) : super(message, cause) {
        this.faultInfo = faultInfo
    }

    companion object {
        private const val serialVersionUID = -7991977127301372277L
    }
}