package br.com.correios.webservice.estimativa

import java.net.URL
import javax.xml.namespace.QName
import javax.xml.ws.Service
import javax.xml.ws.WebEndpoint
import javax.xml.ws.WebServiceClient
import javax.xml.ws.WebServiceFeature

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(
    name = "CalcPrecoPrazoWS",
    targetNamespace = "http://tempuri.org/",
    wsdlLocation = "classpath:wsdl/CalcPrecoPrazo.wsdl"
)
class CalcPrecoPrazoWS : Service {
    companion object {
        private var CALCPRECOPRAZOWS_WSDL_LOCATION: URL? = null
        private val CALCPRECOPRAZOWS_QNAME = QName("http://tempuri.org/", "CalcPrecoPrazoWS")
        private fun __getWsdlLocation(): URL? {
            return CALCPRECOPRAZOWS_WSDL_LOCATION
        }

        init {
            CALCPRECOPRAZOWS_WSDL_LOCATION =
                CalcPrecoPrazoWS::class.java.classLoader.getResource("wsdl/CalcPrecoPrazo.wsdl")
        }
    }

    constructor() : super(__getWsdlLocation(), CALCPRECOPRAZOWS_QNAME) {}
    constructor(vararg features: WebServiceFeature?) : super(__getWsdlLocation(), CALCPRECOPRAZOWS_QNAME, *features) {}
    constructor(wsdlLocation: URL?) : super(wsdlLocation, CALCPRECOPRAZOWS_QNAME) {}
    constructor(wsdlLocation: URL?, vararg features: WebServiceFeature?) : super(
        wsdlLocation,
        CALCPRECOPRAZOWS_QNAME,
        *features
    ) {
    }

    constructor(wsdlLocation: URL?, serviceName: QName?) : super(wsdlLocation, serviceName) {}
    constructor(wsdlLocation: URL?, serviceName: QName?, vararg features: WebServiceFeature?) : super(
        wsdlLocation,
        serviceName,
        *features
    ) {
    }

    @get:WebEndpoint(name = "CalcPrecoPrazoWSSoap")
    val calcPrecoPrazoWSSoap: CalcPrecoPrazoWSSoap
        get() = super.getPort(QName("http://tempuri.org/", "CalcPrecoPrazoWSSoap"), CalcPrecoPrazoWSSoap::class.java)


    @WebEndpoint(name = "CalcPrecoPrazoWSSoap")
    fun getCalcPrecoPrazoWSSoap(vararg features: WebServiceFeature?): CalcPrecoPrazoWSSoap {
        return super.getPort(
            QName("http://tempuri.org/", "CalcPrecoPrazoWSSoap"),
            CalcPrecoPrazoWSSoap::class.java,
            *features
        )
    }
}