package br.com.correios.webservice.estimativa

import java.math.BigDecimal
import javax.jws.*
import javax.xml.bind.annotation.XmlSeeAlso
import javax.xml.ws.RequestWrapper
import javax.xml.ws.ResponseWrapper

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "CalcPrecoPrazoWSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso(ObjectFactory::class)
interface CalcPrecoPrazoWSSoap {

    @WebMethod(operationName = "CalcPrecoPrazo", action = "http://tempuri.org/CalcPrecoPrazo")
    @WebResult(name = "CalcPrecoPrazoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(
        localName = "CalcPrecoPrazo",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoPrazo"
    )
    @ResponseWrapper(
        localName = "CalcPrecoPrazoResponse",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoPrazoResponse"
    )
    @HandlerChain(file = "handlers.xml")
    fun calcPrecoPrazo(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/") nCdEmpresa: String?,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/") sDsSenha: String?,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/") nCdServico: String?,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/") sCepOrigem: String?,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/") sCepDestino: String?,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/") nVlPeso: String?,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/") nCdFormato: Int,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/") nVlComprimento: BigDecimal?,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/") nVlAltura: BigDecimal?,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/") nVlLargura: BigDecimal?,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/") nVlDiametro: BigDecimal?,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/") sCdMaoPropria: String?,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/") nVlValorDeclarado: BigDecimal?,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/") sCdAvisoRecebimento: String?
    ): CResultado?

    @WebMethod(operationName = "CalcPrecoPrazoData", action = "http://tempuri.org/CalcPrecoPrazoData")
    @WebResult(name = "CalcPrecoPrazoDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(
        localName = "CalcPrecoPrazoData",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoPrazoData"
    )
    @ResponseWrapper(
        localName = "CalcPrecoPrazoDataResponse",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoPrazoDataResponse"
    )
    @HandlerChain(file = "handlers.xml")
    fun calcPrecoPrazoData(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/") nCdEmpresa: String?,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/") sDsSenha: String?,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/") nCdServico: String?,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/") sCepOrigem: String?,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/") sCepDestino: String?,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/") nVlPeso: String?,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/") nCdFormato: Int,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/") nVlComprimento: BigDecimal?,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/") nVlAltura: BigDecimal?,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/") nVlLargura: BigDecimal?,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/") nVlDiametro: BigDecimal?,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/") sCdMaoPropria: String?,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/") nVlValorDeclarado: BigDecimal?,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/") sCdAvisoRecebimento: String?,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/") sDtCalculo: String?
    ): CResultado?

    @WebMethod(operationName = "CalcPrecoPrazoRestricao", action = "http://tempuri.org/CalcPrecoPrazoRestricao")
    @WebResult(name = "CalcPrecoPrazoRestricaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(
        localName = "CalcPrecoPrazoRestricao",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoPrazoRestricao"
    )
    @ResponseWrapper(
        localName = "CalcPrecoPrazoRestricaoResponse",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoPrazoRestricaoResponse"
    )
    @HandlerChain(file = "handlers.xml")
    fun calcPrecoPrazoRestricao(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/") nCdEmpresa: String?,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/") sDsSenha: String?,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/") nCdServico: String?,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/") sCepOrigem: String?,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/") sCepDestino: String?,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/") nVlPeso: String?,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/") nCdFormato: Int,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/") nVlComprimento: BigDecimal?,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/") nVlAltura: BigDecimal?,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/") nVlLargura: BigDecimal?,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/") nVlDiametro: BigDecimal?,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/") sCdMaoPropria: String?,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/") nVlValorDeclarado: BigDecimal?,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/") sCdAvisoRecebimento: String?,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/") sDtCalculo: String?
    ): CResultado?

    @WebMethod(operationName = "CalcPreco", action = "http://tempuri.org/CalcPreco")
    @WebResult(name = "CalcPrecoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(
        localName = "CalcPreco",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPreco"
    )
    @ResponseWrapper(
        localName = "CalcPrecoResponse",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoResponse"
    )
    @HandlerChain(file = "handlers.xml")
    fun calcPreco(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/") nCdEmpresa: String?,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/") sDsSenha: String?,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/") nCdServico: String?,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/") sCepOrigem: String?,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/") sCepDestino: String?,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/") nVlPeso: String?,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/") nCdFormato: Int,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/") nVlComprimento: BigDecimal?,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/") nVlAltura: BigDecimal?,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/") nVlLargura: BigDecimal?,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/") nVlDiametro: BigDecimal?,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/") sCdMaoPropria: String?,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/") nVlValorDeclarado: BigDecimal?,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/") sCdAvisoRecebimento: String?
    ): CResultado?

    @WebMethod(operationName = "CalcPrecoData", action = "http://tempuri.org/CalcPrecoData")
    @WebResult(name = "CalcPrecoDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(
        localName = "CalcPrecoData",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoData"
    )
    @ResponseWrapper(
        localName = "CalcPrecoDataResponse",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoDataResponse"
    )
    @HandlerChain(file = "handlers.xml")
    fun calcPrecoData(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/") nCdEmpresa: String?,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/") sDsSenha: String?,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/") nCdServico: String?,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/") sCepOrigem: String?,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/") sCepDestino: String?,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/") nVlPeso: String?,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/") nCdFormato: Int,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/") nVlComprimento: BigDecimal?,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/") nVlAltura: BigDecimal?,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/") nVlLargura: BigDecimal?,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/") nVlDiametro: BigDecimal?,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/") sCdMaoPropria: String?,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/") nVlValorDeclarado: BigDecimal?,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/") sCdAvisoRecebimento: String?,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/") sDtCalculo: String?
    ): CResultado?

    @WebMethod(operationName = "CalcPrazo", action = "http://tempuri.org/CalcPrazo")
    @WebResult(name = "CalcPrazoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(
        localName = "CalcPrazo",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrazo"
    )
    @ResponseWrapper(
        localName = "CalcPrazoResponse",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrazoResponse"
    )
    @HandlerChain(file = "handlers.xml")
    fun calcPrazo(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/") nCdServico: String?,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/") sCepOrigem: String?,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/") sCepDestino: String?
    ): CResultado?

    @WebMethod(operationName = "CalcPrazoData", action = "http://tempuri.org/CalcPrazoData")
    @WebResult(name = "CalcPrazoDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(
        localName = "CalcPrazoData",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrazoData"
    )
    @ResponseWrapper(
        localName = "CalcPrazoDataResponse",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrazoDataResponse"
    )
    @HandlerChain(file = "handlers.xml")
    fun calcPrazoData(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/") nCdServico: String?,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/") sCepOrigem: String?,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/") sCepDestino: String?,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/") sDtCalculo: String?
    ): CResultado?

    @WebMethod(operationName = "CalcPrazoRestricao", action = "http://tempuri.org/CalcPrazoRestricao")
    @WebResult(name = "CalcPrazoRestricaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(
        localName = "CalcPrazoRestricao",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrazoRestricao"
    )
    @ResponseWrapper(
        localName = "CalcPrazoRestricaoResponse",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrazoRestricaoResponse"
    )
    @HandlerChain(file = "handlers.xml")
    fun calcPrazoRestricao(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/") nCdServico: String?,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/") sCepOrigem: String?,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/") sCepDestino: String?,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/") sDtCalculo: String?
    ): CResultado?

    @WebMethod(operationName = "CalcPrecoFAC", action = "http://tempuri.org/CalcPrecoFAC")
    @WebResult(name = "CalcPrecoFACResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(
        localName = "CalcPrecoFAC",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoFAC"
    )
    @ResponseWrapper(
        localName = "CalcPrecoFACResponse",
        targetNamespace = "http://tempuri.org/",
        className = "br.com.correios.webservice.estimativa.CalcPrecoFACResponse"
    )
    @HandlerChain(file = "handlers.xml")
    fun calcPrecoFAC(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/") nCdServico: String?,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/") nVlPeso: String?,
        @WebParam(name = "strDataCalculo", targetNamespace = "http://tempuri.org/") strDataCalculo: String?
    ): CResultado?
}